const rawLocaleStateMap: {state: AustralianState | "", locale: string}[] = [
  { state: 'WA', locale: 'ABRA MINE WA'},
  { state: 'NSW', locale: 'ADAMINABY NSW'},
  { state: 'SA', locale: 'ADELAIDE'},
  { state: 'SA', locale: 'ADELAIDE CENTRE'},
  { state: 'QLD', locale: 'ADELS GROVE QLD'},
  { state: 'WA', locale: 'ALBANY WA'},
  { state: 'NSW', locale: 'ALBURY HRS-SEE NSW'},
  { state: 'SA', locale: 'ALDINGA SA'},
  { state: 'NT', locale: 'ALICE SPRINGS'},
  { state: 'NT', locale: 'ALICE SPRINGS HRS-SEE NT'},
  { state: 'QLD', locale: 'ALPHA QLD'},
  { state: 'SA', locale: 'AMATA SA'},
  { state: 'QLD', locale: 'AMBERLEY'},
  { state: 'QLD', locale: 'AMBERLEY HRS-SEE QLD'},
  { state: 'SA', locale: 'ANNA CREEK SA'},
  { state: 'QLD', locale: 'AQUILA QLD'},
  { state: 'QLD', locale: 'ARAMAC QLD'},
  { state: 'VIC', locale: 'ARARAT VIC'},
  { state: 'WA', locale: 'ARGYLE WA'},
  { state: 'SA', locale: 'ARKAROOLA SA'},
  { state: 'NSW', locale: 'ARMIDALE NSW'},
  { state: 'QLD', locale: 'ARRABURY QLD'},
  { state: 'QLD', locale: 'ATHERTON'},
  { state: 'QLD', locale: 'ATHERTON QLD'},
  { state: 'WA', locale: 'AUGUSTA WA'},
  { state: 'QLD', locale: 'AUGUSTUS DOWNS QLD'},
  { state: 'QLD', locale: 'AURUKUN QLD'},
  { state: 'QLD', locale: 'AUST AGE OF DINOSAURS MUSEUM QLD'},
  { state: 'QLD', locale: 'AKENS ISLAND' },
  { state: 'WA', locale: 'ALAMEIN' },
  { state: 'NSW', locale: 'ALBURY' },
  { state: 'NT', locale: 'ANGALARRI NORTH' },
  { state: 'NT', locale: 'ANGALARRI SOUTH' },
  { state: 'QLD', locale: 'ARCHERFIELD' },
  { state: 'NSW', locale: 'ATTUNGA' },
  { state: 'VIC', locale: 'AVALON' },
  { state: 'VIC', locale: 'AVALON HRS-SEE VIC' },
  { state: 'NT', locale: 'AYERS NT' },
  { state: 'NT', locale: 'AYERS ROCK' },
  { state: 'QLD', locale: 'AYR QLD' },
  { state: 'VIC', locale: 'BACCHUS MARSH' },
  { state: 'VIC', locale: 'BACCHUS MARSH VIC' },
  { state: 'QLD', locale: 'BADU ISLAND QLD' },
  { state: 'VIC', locale: 'BAIRNSDALE VIC' },
  { state: 'SA', locale: 'BALCANOONA SA' },
  { state: 'WA', locale: 'BALGO HILL WA' },
  { state: 'VIC', locale: 'BALLARAT VIC' },
  { state: 'QLD', locale: 'BALLERA' },
  { state: 'QLD', locale: 'BALLERA QLD' },
  { state: 'WA', locale: 'BALLIDU WA' },
  { state: 'NSW', locale: 'BALRANALD NSW' },
  { state: 'NT', locale: 'BAMYILI NT' },
  { state: 'NSW', locale: 'BANKSTOWN' },
  { state: 'NSW', locale: 'BARADINE NSW' },
  { state: 'QLD', locale: 'BARALABA QLD' },
  { state: 'QLD', locale: 'BARCALDINE QLD' },
  { state: 'WA', locale: 'BARIMUNYA WA' },
  { state: 'VIC', locale: 'BARRACOUTA PLATFORM VIC' },
  { state: 'WA', locale: 'BARROW ISLAND' },
  { state: 'WA', locale: 'BARROW ISLAND WA' },
  { state: 'VIC', locale: 'BARWON FIELD VIC' },
  { state: 'VIC', locale: 'BARWON HEADS' },
  { state: 'VIC', locale: 'BARWON VIC' },
  { state: 'NSW', locale: 'BARYULGIL NSW' },
  { state: 'NT', locale: 'BATHURST ISLAND NT' },
  { state: 'NSW', locale: 'BATHURST NSW' },
  { state: 'VIC', locale: 'BATMAN PARK HELIPORT VIC' },
  { state: 'VIC', locale: 'BEAUFORT VIC' },
  { state: 'QLD', locale: 'BEDOURIE QLD' },
  { state: 'NSW', locale: 'BEECROFT HEAD' },
  { state: 'WA', locale: 'BELLBURN WA' },
  { state: 'WA', locale: 'BELLEVUE WA' },
  { state: 'VIC', locale: 'BENALLA' },
  { state: 'VIC', locale: 'BENALLA VIC' },
  { state: 'VIC', locale: 'BENDIGO VIC' },
  { state: 'QLD', locale: 'BETOOTA QLD' },
  { state: 'SA', locale: 'BEVERLEY MINE SA' },
  { state: 'WA', locale: 'BEVERLEY WA' },
  { state: 'WA', locale: 'BINDOON' },
  { state: 'WA', locale: 'BINDOON HILL WA' },
  { state: 'VIC', locale: 'BIRCHIP VIC' },
  { state: 'QLD', locale: 'BIRDSVILLE QLD' },
  { state: 'QLD', locale: 'BLACKALL QLD' },
  { state: 'QLD', locale: 'BLACKWATER QLD' },
  { state: 'NT', locale: 'BLADIN POINT' },
  { state: 'QLD', locale: 'BLOSSOM BANKS QLD' },
  { state: 'QLD', locale: 'BLUEWATER PARK QLD' },
  { state: 'QLD', locale: 'BOLLON QLD' },
  { state: 'NSW', locale: 'BOMBALA NSW' },
  { state: 'NT', locale: 'BOND SPRINGS' },
  { state: 'SA', locale: 'BOOLEROO CENTRE SA' },
  { state: 'WA', locale: 'BOOLGEEDA WA' },
  { state: 'NSW', locale: 'BOOMI NSW' },
  { state: 'QLD', locale: 'BOONAH QLD' },
  { state: 'VIC', locale: 'BOORT VIC' },
  { state: 'SA', locale: 'BORDERTOWN SA' },
  { state: 'NT', locale: 'BORROLOOLA NT' },
  { state: 'QLD', locale: 'BOULIA QLD' },
  { state: 'NSW', locale: 'BOURKE NSW' },
  { state: 'QLD', locale: 'BOWEN QLD' },
  { state: 'NSW', locale: 'BREWARRINA NSW' },
  { state: 'VIC', locale: 'BRIDGEWATER VIC' },
  { state: 'QLD', locale: 'BRISBANE' },
  { state: 'QLD', locale: 'BRISBANE CENTRE' },
  { state: 'QLD', locale: 'BRISBANE WEST WELLCAMP' },
  { state: 'QLD', locale: 'BRISBANE WEST WELLCAMP QLD' },
  { state: 'NSW', locale: 'BROKEN HILL NSW' },
  { state: 'SA', locale: 'BROOKLANDS' },
  { state: 'WA', locale: 'BROOME' },
  { state: 'WA', locale: 'BROWNS RANGE WA' },
  { state: 'WA', locale: 'BROWSE BASIN WA' },
  { state: 'TAS', locale: 'BRUNY ISLAND TAS' },
  { state: 'TAS', locale: 'BUCKLAND' },
  { state: 'TAS', locale: 'BUCKLAND PARK' },
  { state: 'WA', locale: 'BUNBURY WA' },
  { state: 'QLD', locale: 'BUNDABERG' },
  { state: 'QLD', locale: 'BUNDABERG QLD' },
  { state: 'QLD', locale: 'BURKETOWN QLD' },
  { state: 'SA', locale: 'BURRA' },
  { state: 'WA', locale: 'BUSSELTON WA' },
  { state: 'NSW', locale: 'BYROCK' },
  { state: 'QLD', locale: 'CABOOLTURE QLD' },
  { state: 'NSW', locale: 'CADIA GOLD MINE' },
  { state: 'SA', locale: 'CADNEY HOMESTEAD SA' },
  { state: 'WA', locale: 'CAIGUNA WA' },
  { state: 'QLD', locale: 'CAIRNS' },
  { state: 'QLD', locale: 'CAIRNS APPROACH' },
  { state: 'QLD', locale: 'CALOUNDRA QLD' },
  { state: 'SA', locale: 'CALVIN GROVE SA' },
  { state: 'NSW', locale: 'CAMDEN' },
  { state: 'NSW', locale: 'CAMDEN HAVEN NSW' },
  { state: 'NSW', locale: 'CAMDEN HRS-SEE NSW' },
  { state: 'QLD', locale: 'CAMOOWEAL QLD' },
  { state: 'ACT', locale: 'CANBERRA' },
  { state: 'ACT', locale: 'CANBERRA APPROACH' },
  { state: 'ACT', locale: 'CANBERRA HRS-SEE ACT' },
  { state: 'QLD', locale: 'CANUNGRA' },
  { state: 'QLD', locale: 'CAPE CLEVELAND' },
  { state: 'QLD', locale: 'CAPE CLINTON' },
  { state: 'WA', locale: 'CAPE LEVEQUE WA' },
  { state: 'WA', locale: 'CAPE PRESTON WA' },
  { state: 'VIC', locale: 'CAPE SCHANCK' },
  { state: 'QLD', locale: 'CAPELLA QLD' },
  { state: 'WA', locale: 'CARNARVON WA' },
  { state: 'WA', locale: 'CAROSUE DAM WA' },
  { state: 'SA', locale: 'CARRAPATEENA SA' },
  { state: 'NSW', locale: 'CASINO NSW' },
  { state: 'VIC', locale: 'CASTERTON VIC' },
  { state: 'QLD', locale: 'CEDAR GROVE' },
  { state: 'SA', locale: 'CEDUNA SA' },
  { state: 'QLD', locale: 'CENTURY MINE QLD' },
  { state: 'NSW', locale: 'CESSNOCK NSW' },
  { state: 'QLD', locale: 'CHARLEVILLE QLD' },
  { state: 'WA', locale: 'CHARLIE ONE WA' },
  { state: 'QLD', locale: 'CHARTERS TOWERS QLD' },
  { state: 'QLD', locale: 'CHILLAGOE QLD' },
  { state: 'QLD', locale: 'CHINCHILLA QLD' },
  { state: 'WA', locale: 'CHRISTMAS CREEK WA' },
  { state: 'OTHER', locale: 'CHRISTMAS ISLAND OTH' },
  { state: 'SA', locale: 'CLARE VALLEY SA' },
  { state: 'QLD', locale: 'CLERMONT QLD' },
  { state: 'SA', locale: 'CLEVE SA' },
  { state: 'QLD', locale: 'CLIFTON QLD' },
  { state: 'QLD', locale: 'CLONCURRY QLD' },
  { state: 'QLD', locale: 'CLUNY QLD' },
  { state: 'QLD', locale: 'COAST QLD' },
  { state: 'NSW', locale: 'COBAR NSW' },
  { state: 'VIC', locale: 'COBDEN VIC' },
  { state: 'WA', locale: 'COCKATOO ISLAND WA' },
  { state: 'QLD', locale: 'COCONUT ISLAND QLD' },
  { state: 'OTHER', locale: 'COCOS ISLANDS OTH' },
  { state: 'QLD', locale: 'COEN QLD' },
  { state: 'SA', locale: 'COFFIN BAY SA' },
  { state: 'NSW', locale: 'COFFS HARBOUR' },
  { state: 'NSW', locale: 'COFFS HARBOUR HRS-SEE NSW' },
  { state: 'VIC', locale: 'COHUNA VIC' },
  { state: 'VIC', locale: 'COLAC VIC' },
  { state: 'VIC', locale: 'COLDSTREAM VIC' },
  { state: 'NSW', locale: 'COLLARENEBRI NSW' },
  { state: 'QLD', locale: 'COLLINSVILLE QLD' },
  { state: 'NSW', locale: 'CONDOBOLIN NSW' },
  { state: 'OTHER', locale: 'CONTINENTAL AUSTRALIA' },
  { state: 'SA', locale: 'COOBER PEDY SA' },
  { state: 'NT', locale: 'COOINDA NT' },
  { state: 'QLD', locale: 'COOKTOWN QLD' },
  { state: 'NSW', locale: 'COOLAH NSW' },
  { state: 'NSW', locale: 'COOLATAI NSW' },
  { state: 'NT', locale: 'COOLIBAH CORRIDOR NORTH' },
  { state: 'NT', locale: 'COOLIBAH CORRIDOR SOUTH' },
  { state: 'WA', locale: 'COOLILUP' },
  { state: 'NSW', locale: 'COOMA POLO FLAT NSW' },
  { state: 'NSW', locale: 'COOMA SNOWY MOUNTAINS NSW' },
  { state: 'NSW', locale: 'COOMBING PARK NSW' },
  { state: 'QLD', locale: 'COOMINYA QLD' },
  { state: 'NSW', locale: 'COONABARABRAN NSW' },
  { state: 'NSW', locale: 'COONAMBLE NSW' },
  { state: 'WA', locale: 'COONDEWANNA WA' },
  { state: 'NSW', locale: 'COOTAMUNDRA NSW' },
  { state: 'NSW', locale: 'COROWA NSW' },
  { state: 'VIC', locale: 'CORRYONG VIC' },
  { state: 'SA', locale: 'COWELL SA' },
  { state: 'NSW', locale: 'COWRA NSW' },
  { state: 'NT', locale: 'COX PENINSULA' },
  { state: 'TAS', locale: 'CRANBOURN TAS' },
  { state: 'VIC', locale: 'CRESSY VIC' },
  { state: 'NT', locale: 'CROKER ISLAND NT' },
  { state: 'NSW', locale: 'CROOKWELL NSW' },
  { state: 'QLD', locale: 'CROYDON QLD' },
  { state: 'WA', locale: 'CUE WA' },
  { state: 'NSW', locale: 'CULGOORA' },
  { state: 'SA', locale: 'CULTANA' },
  { state: 'SA', locale: 'CUMMINS TOWN SA' },
  { state: 'WA', locale: 'CUNDERDIN WA' },
  { state: 'QLD', locale: 'CUNNAMULLA QLD' },
  { state: 'WA', locale: 'CURTIN' },
  { state: 'WA', locale: 'CURTIN HRS-SEE WA' },
  { state: 'QLD', locale: 'CURTIS ISLAND' },
  { state: 'QLD', locale: 'DALBY QLD' },
  { state: 'WA', locale: 'DALGARANGA MINE WA' },
  { state: 'WA', locale: 'DARLOT WA' },
  { state: 'NT', locale: 'DARWIN' },
  { state: 'QLD', locale: 'DAVENPORT DOWNS QLD' },
  { state: 'WA', locale: 'DEGRUSSA WA' },
  { state: 'NT', locale: 'DELAMERE' },
  { state: 'NT', locale: 'DELAMERE RANGE FACILITY NT' },
  { state: 'NT', locale: 'DELISSAVILLE NT' },
  { state: 'QLD', locale: 'DELTA DOWNS QLD' },
  { state: 'NSW', locale: 'DENILIQUIN NSW' },
  { state: 'NSW', locale: 'DENMAN' },
  { state: 'WA', locale: 'DENMARK WA' },
  { state: 'WA', locale: 'DERBY HRS-SEE WA' },
  { state: 'TAS', locale: 'DEVONPORT TAS' },
  { state: 'QLD', locale: 'DIRRANBANDI QLD' },
  { state: 'NSW', locale: 'DOCHRA NSW' },
  { state: 'NT', locale: 'DOCKER RIVER NT' },
  { state: 'VIC', locale: 'DOLPHIN PLATFORM VIC' },
  { state: 'VIC', locale: 'DONALD VIC' },
  { state: 'QLD', locale: 'DONNINGTON AIRPARK QLD' },
  { state: 'QLD', locale: 'DOOMADGEE QLD' },
  { state: 'QLD', locale: 'DORUNDA STATION QLD' },
  { state: 'VIC', locale: 'DROUIN VIC' },
  { state: 'WA', locale: 'DRYSDALE RIVER WA' },
  { state: 'NSW', locale: 'DUBBO NSW' },
  { state: 'WA', locale: 'DUKETON GOLD WA' },
  { state: 'WA', locale: 'DUMBLEYUNG WA' },
  { state: 'QLD', locale: 'DUNBAR QLD' },
  { state: 'QLD', locale: 'DUNK ISLAND QLD' },
  { state: 'QLD', locale: 'DUNWICH QLD' },
  { state: 'QLD', locale: 'DURHAM DOWNS QLD' },
  { state: 'QLD', locale: 'DURRIE QLD' },
  { state: 'VIC', locale: 'DUTSON' },
  { state: 'QLD', locale: 'DYSART QLD' },
  { state: 'OTHER', locale: 'EAST COAST' },
  { state: 'WA', locale: 'EAST JAURDI WA' },
  { state: 'VIC', locale: 'EAST SALE' },
  { state: 'VIC', locale: 'EAST SALE HRS-SEE VIC' },
  { state: 'VIC', locale: 'ECHUCA VIC' },
  { state: 'WA', locale: 'ECO BEACH WA' },
  { state: 'SA', locale: 'EDINBURGH' },
  { state: 'SA', locale: 'EDINBURGH HRS-SEE SA' },
  { state: 'QLD', locale: 'EIDSVOLD QLD' },
  { state: 'NT', locale: 'ELCHO ISLAND NT' },
  { state: 'WA', locale: 'ELIWANA WA' },
  { state: 'NT', locale: 'ELLIOTT' },
  { state: 'SA', locale: 'ELLISTON SA' },
  { state: 'QLD', locale: 'ELROSE QLD' },
  { state: 'QLD', locale: 'EMERALD QLD' },
  { state: 'NT', locale: 'EMKAYTEE NT' },
  { state: 'QLD', locale: 'EMU PARK QLD' },
  { state: 'QLD', locale: 'ENOGGERA HELIPORT QLD' },
  { state: 'NSW', locale: 'ERINA HELIPORT NSW' },
  { state: 'SA', locale: 'ERNABELLA SA' },
  { state: 'QLD', locale: 'EROMANGA QLD' },
  { state: 'WA', locale: 'ESPERANCE WA' },
  { state: 'QLD', locale: 'EULO QLD' },
  { state: 'VIC', locale: 'EUROA'},
  { state: 'VIC', locale: 'EUROA VIC' },
  { state: 'VIC', locale: 'EUROA VIC' },
  { state: 'NSW', locale: 'EVANS HEAD' },
  { state: 'NSW', locale: 'EVANS HEAD NSW' },
  { state: 'WA', locale: 'EXMOUTH WA' },
  { state: 'QLD', locale: 'FACING ISLAND QLD' },
  { state: 'TAS', locale: 'FARM TAS' },
  { state: 'NSW', locale: 'FEDERATION NSW' },
  { state: 'NSW', locale: 'FIELDS NSW' },
  { state: 'WA', locale: 'FITZROY CROSSING WA' },
  { state: 'TAS', locale: 'FLINDERS ISLAND TAS' },
  { state: 'NSW', locale: 'FORBES NSW' },
  { state: 'WA', locale: 'FORREST WA' },
  { state: 'WA', locale: 'FORRESTANIA WA' },
  { state: 'WA', locale: 'FORTESCUE DAVE FORREST WA' },
  { state: 'SA', locale: 'FREGON SA' },
  { state: 'WA', locale: 'GARDEN ISLAND' },
  { state: 'WA', locale: 'GARDEN ISLAND HELIPORT WA' },
  { state: 'NT', locale: 'GARDEN POINT NT' },
  { state: 'NSW', locale: 'GATEWAY NSW' },
  { state: 'QLD', locale: 'GATTON AIRPARK QLD' },
  { state: 'SA', locale: 'GAWLER GLIDING' },
  { state: 'SA', locale: 'GAWLER SA' },
  { state: 'QLD', locale: 'GAYNDAH' },
  { state: 'QLD', locale: 'GAYNDAH QLD' },
  { state: 'TAS', locale: 'GEORGE TOWN TAS' },
  { state: 'QLD', locale: 'GEORGETOWN QLD' },
  { state: 'WA', locale: 'GERALDTON WA' },
  { state: 'WA', locale: 'GIBB RIVER WA' },
  { state: 'WA', locale: 'GILES WA' },
  { state: 'NSW', locale: 'GILGANDRA NSW' },
  { state: 'WA', locale: 'GINBATA WA' },
  { state: 'WA', locale: 'GINGIN HRS-SEE WA' },
  { state: 'NT', locale: 'GIRRAWEEN'},
  { state: 'QLD', locale: 'GLADSTONE' },
  { state: 'QLD', locale: 'GLADSTONE QLD' },
  { state: 'QLD', locale: 'GLASSHOUSE' },
  { state: 'NSW', locale: 'GLEN INNES NSW' },
  { state: 'VIC', locale: 'GLENAMPLE HELIPORT VIC' },
  { state: 'NSW', locale: 'GLENBROOK HLS NSW' },
  { state: 'QLD', locale: 'GLENORMISTON QLD' },
  { state: 'VIC', locale: 'GNARWARRE VIC' },
  { state: 'WA', locale: 'GNOWANGERUP WA' },
  { state: 'QLD', locale: 'GOLD COAST' },
  { state: 'QLD', locale: 'GOLD COAST HRS-SEE QLD' },
  { state: 'WA', locale: 'GOLDEN GROVE WA' },
  { state: 'NSW', locale: 'GOODOOGA NSW' },
  { state: 'WA', locale: 'GOODWYN ALPHA' },
  { state: 'NSW', locale: 'GOOLGOWI NSW' },
  { state: 'SA', locale: 'GOOLWA SA' },
  { state: 'QLD', locale: 'GOONDIWINDI QLD' },
  { state: 'NSW', locale: 'GOSFORD HOSPITAL NSW' },
  { state: 'NSW', locale: 'GOULBURN NSW' },
  { state: 'NT', locale: 'GOVE NT' },
  { state: 'NSW', locale: 'GRAFTON NSW' },
  { state: 'VIC', locale: 'GRAYTOWN' },
  { state: 'VIC', locale: 'GREAT LAKES AIRFIELD VIC' },
  { state: 'QLD', locale: 'GREENBANK' },
  { state: 'QLD', locale: 'GREENVALE TRAINING AREA' },
  { state: 'QLD', locale: 'GREGORY DOWNS QLD' },
  { state: 'NSW', locale: 'GRIFFITH NSW' },
  { state: 'NT', locale: 'GROOTE EYLANDT NT' },
  { state: 'WA', locale: 'GRUYERE WA' },
  { state: 'WA', locale: 'GUDAI-DARRI MINE WA' },
  { state: 'VIC', locale: 'GUNBOWER VIC' },
  { state: 'NSW', locale: 'GUNDAROO NSW' },
  { state: 'QLD', locale: 'GUNNEDAH' },
  { state: 'NSW', locale: 'GUNNEDAH NSW' },
  { state: 'QLD', locale: 'GYMPIE QLD' },
  { state: 'NT', locale: 'HAASTS BLUFF NT' },
  { state: 'WA', locale: 'HALLS CREEK WA' },
  { state: 'QLD', locale: 'HAMILTON IS' },
  { state: 'QLD', locale: 'HAMILTON ISLAND HRS-SEE QLD' },
  { state: 'VIC', locale: 'HAMILTON VIC' },
  { state: 'VIC', locale: 'HANNS INLET' },
  { state: 'NSW', locale: 'HARDEN NSW' },
  { state: 'SA', locale: 'HAWKER SA' },
  { state: 'NSW', locale: 'HAY NSW' },
  { state: 'QLD', locale: 'HECK FIELD QLD' },
  { state: 'QLD', locale: 'HERBERTVALE CATTLEYARD QLD' },
  { state: 'NT', locale: 'HERMANNSBURG NT' },
  { state: 'QLD', locale: 'HERVEY BAY QLD' },
  { state: 'NSW', locale: 'HILLSTON NSW' },
  { state: 'TAS', locale: 'HOBART' },
  { state: 'TAS', locale: 'HOBART CENTRE' },
  { state: 'TAS', locale: 'HOBART HRS-SEE TAS' },
  { state: 'NSW', locale: 'HOLBROOK NSW' },
  { state: 'NSW', locale: 'HOLSWORTHY' },
  { state: 'NSW', locale: 'HOLSWORTHY NSW' },
  { state: 'VIC', locale: 'HOMESGLEN VIC' },
  { state: 'SA', locale: 'HONEYMOON SA' },
  { state: 'NT', locale: 'HOOKER CREEK NT' },
  { state: 'VIC', locale: 'HOPETOUN VIC' },
  { state: 'QLD', locale: 'HORN ISLAND QLD' },
  { state: 'VIC', locale: 'HORSHAM VIC' },
  { state: 'NSW', locale: 'HRS-SEE NSW' },
  { state: 'QLD', locale: 'HRS-SEE QLD' },
  { state: 'SA', locale: 'HRS-SEE SA' },
  { state: 'TAS', locale: 'HRS-SEE TAS' },
  { state: 'VIC', locale: 'HRS-SEE VIC' },
  { state: 'WA', locale: 'HRS-SEE WA' },
  { state: 'QLD', locale: 'HUGHENDEN QLD' },
  { state: 'QLD', locale: 'HUNGERFORD QLD' },
  { state: 'QLD', locale: 'IFFLEY QLD' },
  { state: 'QLD', locale: 'ILFRACOMBE QLD' },
  { state: 'QLD', locale: 'INGHAM QLD' },
  { state: 'QLD', locale: 'INJUNE QLD' },
  { state: 'QLD', locale: 'INKERMAN STATION QLD' },
  { state: 'SA', locale: 'INNAMINCKA SA' },
  { state: 'SA', locale: 'INNAMINCKA TOWNSHIP SA' },
  { state: 'QLD', locale: 'INTL HRS-SEE QLD JOINT' },
  { state: 'NSW', locale: 'INVERELL NSW' },
  { state: 'WA', locale: 'IRON BRIDGE MINE WA' },
  { state: 'SA', locale: 'IRON MINES' },
  { state: 'QLD', locale: 'ISISFORD QLD' },
  { state: 'SA', locale: 'ISLAND SA' },
  { state: 'NSW', locale: 'IVANHOE NSW' },
  { state: 'NT', locale: 'JABIRU' },
  { state: 'NT', locale: 'JABIRU NT' },
  { state: 'SA', locale: 'JACINTH AMBROSIA SA' },
  { state: 'SA', locale: 'JAMESTOWN SA' },
  { state: 'WA', locale: 'JANDAKOT' },
  { state: 'NSW', locale: 'JERILDERIE NSW' },
  { state: 'NSW', locale: 'JERVIS BAY NSW' },
  { state: 'NSW', locale: 'JINDABYNE NSW' },
  { state: 'QLD', locale: 'JULIA CREEK QLD' },
  { state: 'QLD', locale: 'JUNDAH QLD' },
  { state: 'WA', locale: 'JUNDEE WA' },
  { state: 'WA', locale: 'JURIEN BAY' },
  { state: 'WA', locale: 'JURIEN BAY WA' },
  { state: 'SA', locale: 'KADINA SA' },
  { state: 'WA', locale: 'KALBARRI WA' },
  { state: 'WA', locale: 'KALGOORLIE-BOULDER WA' },
  { state: 'NT', locale: 'KALKGURUNG NT' },
  { state: 'WA', locale: 'KALUMBURU WA' },
  { state: 'WA', locale: 'KAMBALDA WA' },
  { state: 'QLD', locale: 'KAMILEROI QLD' },
  { state: 'VIC', locale: 'KANGAROO FLAT' },
  { state: 'NSW', locale: 'KAPOOKA' },
  { state: 'WA', locale: 'KARARA WA' },
  { state: 'WA', locale: 'KARLAWINDA MINE WA' },
  { state: 'WA', locale: 'KARRATHA' },
  { state: 'WA', locale: 'KARRATHA DAMPIER' },
  { state: 'WA', locale: 'KARRATHA HRS-SEE WA' },
  { state: 'QLD', locale: 'KARUMBA QLD' },
  { state: 'WA', locale: 'KATANNING WA' },
  { state: 'SA', locale: 'KEITH SA' },
  { state: 'NSW', locale: 'KEMPSEY NSW' },
  { state: 'WA', locale: 'KENS BORE WA' },
  { state: 'VIC', locale: 'KERANG VIC' },
  { state: 'QLD', locale: 'KHOLO HELIPAD QLD' },
  { state: 'NT', locale: 'KIDMAN SPRINGS NT' },
  { state: 'QLD', locale: 'KIDSTON QLD' },
  { state: 'QLD', locale: 'KILCOY QLD' },
  { state: 'NT', locale: 'KILLARNEY NT' },
  { state: 'SA', locale: 'KIMBA SA' },
  { state: 'WA', locale: 'KIN KIN RETREAT WA' },
  { state: 'NT', locale: 'KING ASH BAY NT' },
  { state: 'TAS', locale: 'KING ISLAND TAS' },
  { state: 'QLD', locale: 'KINGAROY' },
  { state: 'QLD', locale: 'KINGAROY QLD' },
  { state: 'NT', locale: 'KINGS CREEK STN NT' },
  { state: 'SA', locale: 'KINGSTON SA' },
  { state: 'WA', locale: 'KONDININ WA' },
  { state: 'WA', locale: 'KOOLAN CENTRAL WA' },
  { state: 'WA', locale: 'KOOLAN ISLAND' },
  { state: 'WA', locale: 'KOOLENDONG' },
  { state: 'QLD', locale: 'KOORALBYN QLD' },
  { state: 'QLD', locale: 'KOWANYAMA QLD' },
  { state: 'QLD', locale: 'KUBIN QLD' },
  { state: 'WA', locale: 'KUNUNURRA WA' },
  { state: 'VIC', locale: 'KYNETON VIC' },
  { state: 'NSW', locale: 'LAKE CARGELLIGO NSW' },
  { state: 'NT', locale: 'LAKE EVELLA NT' },
  { state: 'SA', locale: 'LAKE HART' },
  { state: 'NSW', locale: 'LAKE KEEPIT NSW' },
  { state: 'NSW', locale: 'LAKE MACQUARIE AIRPORT NSW' },
  { state: 'QLD', locale: 'LAKELAND DOWNS QLD' },
  { state: 'VIC', locale: 'LAKES ENTRANCE VIC' },
  { state: 'QLD', locale: 'LAKESIDE AIRPARK QLD' },
  { state: 'WA', locale: 'LANCELIN' },
  { state: 'VIC', locale: 'LANDING VIC' },
  { state: 'VIC', locale: 'LANG LANG' },
  { state: 'VIC', locale: 'LANGHORNE' },
  { state: 'VIC', locale: 'LATROBE VALLEY VIC' },
  { state: 'TAS', locale: 'LAUNCESTON' },
  { state: 'TAS', locale: 'LAUNCESTON CENTRE' },
  { state: 'TAS', locale: 'LAUNCESTON HRS-SEE TAS' },
  { state: 'WA', locale: 'LAVERTON' },
  { state: 'WA', locale: 'LAVERTON WA' },
  { state: 'WA', locale: 'LAWLERS WA' },
  { state: 'QLD', locale: 'LAWN HILL QLD' },
  { state: 'WA', locale: 'LEARMONTH' },
  { state: 'WA', locale: 'LEARMONTH WA' },
  { state: 'NT', locale: 'LEGUNE STN NT' },
  { state: 'SA', locale: 'LEIGH CREEK SA' },
  { state: 'WA', locale: 'LEINSTER WA' },
  { state: 'VIC', locale: 'LEONGATHA VIC' },
  { state: 'WA', locale: 'LEONORA WA' },
  { state: 'VIC', locale: 'LETHBRIDGE AIRPORT VIC' },
  { state: 'NSW', locale: 'LIGHTNING RIDGE NSW' },
  { state: 'VIC', locale: 'LILYDALE VIC' },
  { state: 'NSW', locale: 'LISMORE NSW' },
  { state: 'QLD', locale: 'LIZARD ISLAND' },
  { state: 'QLD', locale: 'LIZARD ISLAND QLD' },
  { state: 'QLD', locale: 'LOCKHART RIVER QLD' },
  { state: 'VIC', locale: 'LOCKSLEY FIELD VIC' },
  { state: 'TAS', locale: 'LONGDOWN TAS' },
  { state: 'VIC', locale: 'LONGFORD HELIPORT VIC' },
  { state: 'QLD', locale: 'LONGREACH' },
  { state: 'QLD', locale: 'LONGREACH QLD' },
  { state: 'NSW', locale: 'LORD HOWE ISLAND NSW' },
  { state: 'QLD', locale: 'LORRAINE QLD' },
  { state: 'QLD', locale: 'LOTUS VALE STN QLD' },
  { state: 'NSW', locale: 'LOUTH NSW' },
  { state: 'SA', locale: 'LOWER LIGHT SA' },
  { state: 'SA', locale: 'LOXTON SA' },
  { state: 'NSW', locale: 'LUCAS HEIGHTS' },
  { state: 'SA', locale: 'LYNDOCH SA' },
  { state: 'QLD', locale: 'MACKAY' },
  { state: 'QLD', locale: 'MACKAY HRS-SEE QLD' },
  { state: 'NSW', locale: 'MACLEAN HOSPITAL NSW' },
  { state: 'NSW', locale: 'MAITLAND NSW' },
  { state: 'SA', locale: 'MAITLAND SA' },
  { state: 'ACT', locale: 'MAJURA NORTH' },
  { state: 'ACT', locale: 'MAJURA SOUTH' },
  { state: 'VIC', locale: 'MALLACOOTA VIC' },
  { state: 'VIC', locale: 'MANGALORE' },
  { state: 'VIC', locale: 'MANGALORE VIC' },
  { state: 'NSW', locale: 'MANGROVE MOUNTAIN GLIDING NSW' },
  { state: 'NT', locale: 'MANINGRIDA NT' },
  { state: 'WA', locale: 'MANJIMUP WA' },
  { state: 'VIC', locale: 'MANSFIELD VIC' },
  { state: 'WA', locale: 'MARBLE BAR WA' },
  { state: 'QLD', locale: 'MAREEBA QLD' },
  { state: 'WA', locale: 'MARGARET RIVER WA' },
  { state: 'SA', locale: 'MARLA SA' },
  { state: 'NSW', locale: 'MARRANGAROO' },
  { state: 'SA', locale: 'MARREE SA' },
  { state: 'NSW', locale: 'MARULAN' },
  { state: 'QLD', locale: 'MARYBOROUGH' },
  { state: 'QLD', locale: 'MARYBOROUGH QLD' },
  { state: 'VIC', locale: 'MARYBOROUGH VIC' },
  { state: 'NT', locale: 'MCARTHUR RIVER MINE' },
  { state: 'NT', locale: 'MCARTHUR RIVER MINE NT' },
  { state: 'WA', locale: 'MEEKATHARRA WA' },
  { state: 'VIC', locale: 'MELBOURNE' },
  { state: 'VIC', locale: 'MELBOURNE CENTRE' },
  { state: 'VIC', locale: 'MELTON VIC' },
  { state: 'NT', locale: 'MEREENIE NT' },
  { state: 'NSW', locale: 'MERIMBULA NSW' },
  { state: 'WA', locale: 'MERREDIN WA' },
  { state: 'NSW', locale: 'MERRIWA HOSPITAL NSW' },
  { state: 'QLD', locale: 'MICHAELMAS CAY' },
  { state: 'NT', locale: 'MICKET CREEK' },
  { state: 'QLD', locale: 'MIDDLEBACK' },
  { state: 'QLD', locale: 'MIDDLEMOUNT QLD' },
  { state: 'VIC', locale: 'MILDURA VIC' },
  { state: 'QLD', locale: 'MILES QLD' },
  { state: 'NT', locale: 'MILINGIMBI NT' },
  { state: 'QLD', locale: 'MILL IRON QLD' },
  { state: 'SA', locale: 'MILLICENT SA' },
  { state: 'QLD', locale: 'MILLMERRAN QLD' },
  { state: 'WA', locale: 'MINDEROO WA' },
  { state: 'SA', locale: 'MINNIPA SA' },
  { state: 'QLD', locale: 'MITCHELL QLD' },
  { state: 'VIC', locale: 'MITTA MITTA VIC' },
  { state: 'NSW', locale: 'MITTAGONG NSW' },
  { state: 'NSW', locale: 'MOAMA NSW' },
  { state: 'VIC', locale: 'MODEWARRE VIC' },
  { state: 'SA', locale: 'MONARTO SAFARI PARK SA' },
  { state: 'QLD', locale: 'MONKIRA QLD' },
  { state: 'QLD', locale: 'MONTO QLD' },
  { state: 'SA', locale: 'MOOMBA' },
  { state: 'SA', locale: 'MOOMBA SA' },
  { state: 'VIC', locale: 'MOORABBIN' },
  { state: 'VIC', locale: 'MORAN RESERVE' },
  { state: 'QLD', locale: 'MORANBAH QLD' },
  { state: 'WA', locale: 'MORAWA WA' },
  { state: 'NSW', locale: 'MOREE NSW' },
  { state: 'QLD', locale: 'MORNEY QLD' },
  { state: 'QLD', locale: 'MORNINGTON ISLAND QLD' },
  { state: 'NSW', locale: 'MORUYA NSW' },
  { state: 'VIC', locale: 'MOUNT BEAUTY VIC' },
  { state: 'NT', locale: 'MOUNT BUNDEY NT' },
  { state: 'QLD', locale: 'MOUNT COOLON QLD' },
  { state: 'SA', locale: 'MOUNT GAMBIER SA' },
  { state: 'QLD', locale: 'MOUNT GORDON QLD' },
  { state: 'WA', locale: 'MOUNT HOLLAND WA' },
  { state: 'VIC', locale: 'MOUNT HOTHAM VIC' },
  { state: 'WA', locale: 'MOUNT HOUSE WA' },
  { state: 'QLD', locale: 'MOUNT HOWITT QLD' },
  { state: 'QLD', locale: 'MOUNT HUMMOCK' },
  { state: 'QLD', locale: 'MOUNT ISA' },
  { state: 'QLD', locale: 'MOUNT ISA QLD' },
  { state: 'WA', locale: 'MOUNT KEITH WA' },
  { state: 'WA', locale: 'MOUNT MAGNET' },
  { state: 'WA', locale: 'MOUNT MAGNET WA' },
  { state: 'NT', locale: 'MOUNT SANFORD STATION NT' },
  { state: 'QLD', locale: 'MOURA QLD' },
  { state: 'NT', locale: 'MT BUNDEY' },
  { state: 'QLD', locale: 'MT STUART' },
  { state: 'TAS', locale: 'MT WELLINGTON' },
  { state: 'WA', locale: 'MUCHEA RANGE' },
  { state: 'NSW', locale: 'MUDGEE NSW' },
  { state: 'WA', locale: 'MULLEWA WA' },
  { state: 'NSW', locale: 'MULWALA' },
  { state: 'QLD', locale: 'MUNDUBBERA QLD' },
  { state: 'NSW', locale: 'MUNGINDI NSW' },
  { state: 'NSW', locale: 'MUNGO LODGE NSW' },
  { state: 'QLD', locale: 'MURGON QLD' },
  { state: 'SA', locale: 'MURRAY BRIDGE' },
  { state: 'SA', locale: 'MURRAY BRIDGE SA' },
  { state: 'WA', locale: 'MURRAY FIELD WA' },
  { state: 'WA', locale: 'MURRIN MURRIN WA' },
  { state: 'NSW', locale: 'MURWILLUMBAH NSW' },
  { state: 'QLD', locale: 'MUTTABURRA QLD' },
  { state: 'WA', locale: 'MYRUP WA' },
  { state: 'NT', locale: 'NACKEROO NT' },
  { state: 'VIC', locale: 'NAGAMBIE-WIRRATE VIC' },
  { state: 'QLD', locale: 'NANANGO QLD' },
  { state: 'QLD', locale: 'NAPPA MERRIE QLD' },
  { state: 'SA', locale: 'NARACOORTE SA' },
  { state: 'WA', locale: 'NAREMBEEN WA' },
  { state: 'NSW', locale: 'NARRABRI NSW' },
  { state: 'NSW', locale: 'NARRANDERA NSW' },
  { state: 'WA', locale: 'NARROGIN WA' },
  { state: 'NSW', locale: 'NARROMINE NSW' },
  { state: 'QLD', locale: 'NELLY BAY QLD' },
  { state: 'NSW', locale: 'NEPEAN AEROSPACE PARK NSW' },
  { state: 'NSW', locale: 'NEWCASTLE REGIONAL HELIPORT NSW' },
  { state: 'NSW', locale: 'NEWCASTLE WESTPAC BASE NSW' },
  { state: 'WA', locale: 'NEWMAN WA' },
  { state: 'NT', locale: 'NGUKURR NT' },
  { state: 'VIC', locale: 'NHILL VIC' },
  { state: 'WA', locale: 'NIFTY WA' },
  { state: 'QLD', locale: 'NOOSA QLD' },
  { state: 'QLD', locale: 'NORMANTON HELIPAD QLD' },
  { state: 'QLD', locale: 'NORMANTON QLD' },
  { state: 'WA', locale: 'NORSEMAN WA' },
  { state: 'WA', locale: 'NORTH EAST ROCK' },
  { state: 'WA', locale: 'NORTH RANKIN' },
  { state: 'WA', locale: 'NORTH WEST CAPE' },
  { state: 'WA', locale: 'NORTHAM WA' },
  { state: 'QLD', locale: 'NORTHERN PENINSULA QLD' },
  { state: 'WA', locale: 'NOVA WA' },
  { state: 'NSW', locale: 'NOWRA' },
  { state: 'NSW', locale: 'NOWRA HRS-SEE NSW' },
  { state: 'WA', locale: 'NULLAGINE WA' },
  { state: 'SA', locale: 'NULLARBOR MOTEL SA' },
  { state: 'NT', locale: 'NUMBULWAR NT' },
  { state: 'NSW', locale: 'NYNGAN NSW' },
  { state: 'QLD', locale: 'OAKEY' },
  { state: 'QLD', locale: 'OAKEY HRS-SEE QLD' },
  { state: 'QLD', locale: 'OAKY CREEK QLD' },
  { state: 'VIC', locale: 'OCEAN ROAD VIC' },
  { state: 'NSW', locale: 'OCHRE ARCH NSW' },
  { state: 'NT', locale: 'OENPELLI NT' },
  { state: 'WA', locale: 'OKHA' },
  { state: 'SA', locale: 'OLYMPIC DAM' },
  { state: 'SA', locale: 'OLYMPIC DAM SA' },
  { state: 'WA', locale: 'ONSLOW' },
  { state: 'WA', locale: 'ONSLOW WA' },
  { state: 'SA', locale: 'OODNADATTA SA' },
  { state: 'NSW', locale: 'ORANGE EAST HELIPORT NSW' },
  { state: 'NSW', locale: 'ORANGE NSW' },
  { state: 'VIC', locale: 'ORBOST VIC' },
  { state: 'NSW', locale: 'ORCHARD HILLS' },
  { state: 'SA', locale: 'ORROROO SA' },
  { state: 'QLD', locale: 'OSBORNE MINE QLD' },
  { state: 'QLD', locale: 'PACIFIC HAVEN QLD' },
  { state: 'QLD', locale: 'PALM ISLAND HRS-SEE QLD' },
  { state: 'NT', locale: 'PAPUNYA NT' },
  { state: 'WA', locale: 'PARABURDOO WA' },
  { state: 'SA', locale: 'PARAFIELD' },
  { state: 'NSW', locale: 'PARKES'},
  { state: 'NSW', locale: 'PARKES NSW' },
  { state: 'NT', locale: 'PBDS' },
  { state: 'WA', locale: 'PEARCE' },
  { state: 'WA', locale: 'PEARCE HRS-SEE WA' },
  { state: 'VIC', locale: 'PENFIELD VIC' },
  { state: 'WA', locale: 'PENNY WA' },
  { state: 'VIC', locale: 'PERCH PLATFORM VIC' },
  { state: 'WA', locale: 'PERTH' },
  { state: 'WA', locale: 'PERTH CENTRE' },
  { state: 'SA', locale: 'PETERBOROUGH SA' },
  { state: 'NSW', locale: 'PETRO STATION NSW' },
  { state: 'VIC', locale: 'PHILLIP ISLAND HELIPORT VIC' },
  { state: 'NT', locale: 'PINE GAP' },
  { state: 'SA', locale: 'PINE LEA' },
  { state: 'QLD', locale: 'PINNARENDI QLD' },
  { state: 'SA', locale: 'PINNAROO SA' },
  { state: 'QLD', locale: 'PITTSWORTH QLD' },
  { state: 'WA', locale: 'PLUTONIC WA' },
  { state: 'VIC', locale: 'POINT COOK' },
  { state: 'VIC', locale: 'POINT COOK VIC' },
  { state: 'NSW', locale: 'POONCARIE NSW' },
  { state: 'VIC', locale: 'POREPUNKAH VIC' },
  { state: 'QLD', locale: 'PORMPURAAW QLD' },
  { state: 'SA', locale: 'PORT AUGUSTA SA' },
  { state: 'VIC', locale: 'PORT CAMPBELL HELIPORT VIC' },
  { state: 'WA', locale: 'PORT HEDLAND WA' },
  { state: 'NT', locale: 'PORT KEATS NT' },
  { state: 'SA', locale: 'PORT LINCOLN SA' },
  { state: 'NSW', locale: 'PORT MACQUARIE NSW' },
  { state: 'VIC', locale: 'PORT PHILLIP BAY' },
  { state: 'SA', locale: 'PORT PIRIE SA' },
  { state: 'WA', locale: 'PORT WA' },
  { state: 'SA', locale: 'PORT WAKEFIELD' },
  { state: 'VIC', locale: 'PORTLAND VIC' },
  { state: 'SA', locale: 'PROMINENT HILL SA' },
  { state: 'VIC', locale: 'PUCKAPUNYAL' },
  { state: 'VIC', locale: 'PUCKAPUNYAL VIC' },
  { state: 'NT', locale: 'PUNGALINA NT' },
  { state: 'NSW', locale: 'PURGA RANGE' },
  { state: 'QLD', locale: 'QLD' },
  { state: 'TAS', locale: 'QUEENSTOWN TAS' },
  { state: 'QLD', locale: 'QUILPIE QLD' },
  { state: 'NSW', locale: 'QUIRINDI NSW' },
  { state: 'SA', locale: 'QUORN SA' },
  { state: 'NT', locale: 'RAMINGINING NT' },
  { state: 'QLD', locale: 'RASPBERRY CREEK' },
  { state: 'QLD', locale: 'RATTLESNAKE ISLAND' },
  { state: 'WA', locale: 'RAVENSTHORPE WA' },
  { state: 'NSW', locale: 'RAYNER PLACE HELIPORT NSW' },
  { state: 'VIC', locale: 'RAYWOOD VIC' },
  { state: 'QLD', locale: 'REDCLIFFE QLD' },
  { state: 'SA', locale: 'RENMARK SA' },
  { state: 'VIC', locale: 'RICHMOND' },
  { state: 'NSW', locale: 'RICHMOND HRS-SEE NSW' },
  { state: 'QLD', locale: 'RICHMOND QLD' },
  { state: 'VIC', locale: 'RIDDELL VIC' },
  { state: 'SA', locale: 'ROBE SA' },
  { state: 'NT', locale: 'ROBERTSON BARRACKS' },
  { state: 'NT', locale: 'ROBERTSON BARRACKS NT' },
  { state: 'QLD', locale: 'ROBINHOOD QLD' },
  { state: 'VIC', locale: 'ROBINVALE VIC' },
  { state: 'QLD', locale: 'ROCHEDALE QLD' },
  { state: 'QLD', locale: 'ROCKHAMPTON' },
  { state: 'QLD', locale: 'ROCKHAMPTON HRS-SEE QLD' },
  { state: 'QLD', locale: 'ROLLESTON QLD' },
  { state: 'QLD', locale: 'ROMA QLD' },
  { state: 'VIC', locale: 'ROMSEY VIC' },
  { state: 'NSW', locale: 'ROSE BAY NSW' },
  { state: 'NSW', locale: 'ROSE VALE NSW' },
  { state: 'QLD', locale: 'ROSEBERTH QLD' },
  { state: 'TAS', locale: 'ROSTELLA TAS' },
  { state: 'WA', locale: 'ROTTNEST ISLAND WA' },
  { state: 'NSW', locale: 'ROYAL NORTH SHORE HOSPITAL NSW' },
  { state: 'NSW', locale: 'ROYAL PRINCE ALFRED HOSPITAL NSW' },
  { state: 'QLD', locale: 'RUTLAND PLAINS QLD' },
  { state: 'NSW', locale: 'RYLSTONE AIRPARK NSW' },
  { state: 'QLD', locale: 'SAINT GEORGE QLD' },
  { state: 'TAS', locale: 'SAINT HELENS TAS' },
  { state: 'NSW', locale: 'SALT ASH' },
  { state: 'QLD', locale: 'SAMARAI QLD' },
  { state: 'QLD', locale: 'SAUMAREZ REEF' },
  { state: 'QLD', locale: 'SCHERGER' },
  { state: 'QLD', locale: 'SCHERGER QLD' },
  { state: 'NSW', locale: 'SCONE NSW' },
  { state: 'NSW', locale: 'SCOTIA SANCTUARY NSW' },
  { state: 'VIC', locale: 'SEA LAKE VIC' },
  { state: 'WA', locale: 'SEABUOY WA' },
  { state: 'WA', locale: 'SERPENTINE' },
  { state: 'WA', locale: 'SERPENTINE WA' },
  { state: 'WA', locale: 'SHARK BAY WA' },
  { state: 'NSW', locale: 'SHELLHARBOUR AIRPORT NSW' },
  { state: 'VIC', locale: 'SHEPPARTON VIC' },
  { state: 'QLD', locale: 'SHOALWATER BAY' },
  { state: 'QLD', locale: 'SHOALWATER BAY WEST' },
  { state: 'QLD', locale: 'SHUTE HRS-SEE QLD' },
  { state: 'NSW', locale: 'SINGLETON' },
  { state: 'NSW', locale: 'SINGLETON NSW' },
  { state: 'NSW', locale: 'SMITHFIELD ENERGY FACILITY' },
  { state: 'TAS', locale: 'SMITHTON TAS' },
  { state: 'NT', locale: 'SNAKE BAY NT' },
  { state: 'WA', locale: 'SOLOMON WA' },
  { state: 'NSW', locale: 'SOMERSBY NSW' },
  { state: 'QLD', locale: 'SOUTH GALWAY QLD' },
  { state: 'NT', locale: 'SOUTH GOULBURN ISLAND NT' },
  { state: 'NSW', locale: 'SOUTH GRAFTON NSW' },
  { state: 'OTHER', locale: 'SOUTH-EASTERN' },
  { state: 'WA', locale: 'SOUTHERN CROSS WA' },
  { state: 'QLD', locale: 'SOUTHPORT QLD' },
  { state: 'QLD', locale: 'SPRING CREEK QLD' },
  { state: 'QLD', locale: 'SPRINGSURE QLD' },
  { state: 'VIC', locale: 'ST ARNAUD VIC' },
  { state: 'NSW', locale: 'ST LEONARDS' },
  { state: 'QLD', locale: 'STANTHORPE QLD' },
  { state: 'VIC', locale: 'STAWELL VIC' },
  { state: 'WA', locale: 'STIRLING' },
  { state: 'SA', locale: 'STIRLING FIELD SA' },
  { state: 'QLD', locale: 'STIRLING STATION QLD' },
  { state: 'SA', locale: 'STONEFIELD GLIDING SA' },
  { state: 'QLD', locale: 'STONEHENGE QLD' },
  { state: 'TAS', locale: 'STONY HEAD' },
  { state: 'TAS', locale: 'STRAHAN TAS' },
  { state: 'SA', locale: 'STREAKY BAY SA' },
  { state: 'NSW', locale: 'SULCOR' },
  { state: 'NSW', locale: 'SUNNYSIDE NSW' },
  { state: 'VIC', locale: 'SUNRAYSIA GLIDING VIC' },
  { state: 'WA', locale: 'SUNRISE DAM WA' },
  { state: 'QLD', locale: 'SUNSHINE COAST' },
  { state: 'QLD', locale: 'SUNSHINE COAST HRS-SEE QLD' },
  { state: 'QLD', locale: 'SURAT QLD' },
  { state: 'QLD', locale: 'SWAMPY' },
  { state: 'NSW', locale: 'SWAN BAY NSW' },
  { state: 'VIC', locale: 'SWAN HILL VIC' },
  { state: 'VIC', locale: 'SWAN ISLAND' },
  { state: 'WA', locale: 'SWANBOURNE' },
  { state: 'NSW', locale: 'SYDNEY' },
  { state: 'NSW', locale: 'SYDNEY CENTRE' },
  { state: 'QLD', locale: 'TAMBO QLD' },
  { state: 'NSW', locale: 'TAMWORTH' },
  { state: 'NSW', locale: 'TAMWORTH HRS-SEE NSW' },
  { state: 'NT', locale: 'TANAMI NT' },
  { state: 'SA', locale: 'TANK HILL' },
  { state: 'QLD', locale: 'TARA QLD' },
  { state: 'NSW', locale: 'TAREE NSW' },
  { state: 'QLD', locale: 'TAROOM QLD' },
  { state: 'OTHER', locale: 'TASMAN SEA' },
  { state: 'TAS', locale: 'TASMANIAN' },
  { state: 'WA', locale: 'TELFER GOLD MINE' },
  { state: 'WA', locale: 'TELFER WA' },
  { state: 'NSW', locale: 'TEMORA' },
  { state: 'NSW', locale: 'TEMORA NSW' },
  { state: 'NT', locale: 'TENNANT CREEK NT' },
  { state: 'NSW', locale: 'TENTERFIELD NSW' },
  { state: 'WA', locale: 'TESSA SHOALS WA' },
  { state: 'QLD', locale: 'THANGOOL QLD' },
  { state: 'QLD', locale: 'THARGOMINDAH QLD' },
  { state: 'NSW', locale: 'THE BALD HILLS' },
  { state: 'NT', locale: 'THE GRANITES NT' },
  { state: 'NSW', locale: 'THE LAKES NSW' },
  { state: 'QLD', locale: 'THE MONUMENT QLD' },
  { state: 'NSW', locale: 'THE OAKS NSW' },
  { state: 'TAS', locale: 'THE VALE TAS' },
  { state: 'QLD', locale: 'THEODORE QLD' },
  { state: 'WA', locale: 'THUNDERBOX WA' },
  { state: 'QLD', locale: 'THYLUNGRA QLD' },
  { state: 'NSW', locale: 'TIBOOBURRA NSW' },
  { state: 'ACT', locale: 'TIDBINBILLA' },
  { state: 'QLD', locale: 'TIGER' },
  { state: 'NSW', locale: 'TILPA NSW' },
  { state: 'NT', locale: 'TIMBER CREEK NT' },
  { state: 'NT', locale: 'TINDAL' },
  { state: 'NT', locale: 'TINDAL HRS-SEE NT' },
  { state: 'NT', locale: 'TINDAL WEDGE' },
  { state: 'NSW', locale: 'TOCUMWAL NSW' },
  { state: 'VIC', locale: 'TOORADIN VIC' },
  { state: 'NSW', locale: 'TOORAWEENAH NSW' },
  { state: 'QLD', locale: 'TOOWOOMBA QLD' },
  { state: 'VIC', locale: 'TORQUAY VIC' },
  { state: 'NSW', locale: 'TOTTENHAM NSW' },
  { state: 'QLD', locale: 'TOWNSHEND ISLAND' },
  { state: 'QLD', locale: 'TOWNSVILLE' },
  { state: 'QLD', locale: 'TOWNSVILLE APPROACH' },
  { state: 'NSW', locale: 'TOWRANG GLIDING NSW' },
  { state: 'NT', locale: 'TRA THUNDER' },
  { state: 'SA', locale: 'TREGALANA CORRIDOR' },
  { state: 'QLD', locale: 'TREPELL QLD' },
  { state: 'QLD', locale: 'TRIANGULAR ISLAND' },
  { state: 'WA', locale: 'TROPICANA WA' },
  { state: 'WA', locale: 'TROUGHTON ISLAND WA' },
  { state: 'SA', locale: 'TRURO FLAT AIRPARK SA' },
  { state: 'WA', locale: 'TRUSCOTT-MUNGALALU WA' },
  { state: 'QLD', locale: 'TULLY' },
  { state: 'QLD', locale: 'TULLY HOSPITAL QLD' },
  { state: 'QLD', locale: 'TULLY QLD' },
  { state: 'SA', locale: 'TUMBY BAY SA' },
  { state: 'NSW', locale: 'TUMUT NSW' },
  { state: 'QLD', locale: 'TURTLE PARK QLD' },
  { state: 'VIC', locale: 'TYABB VIC' },
  { state: 'NSW', locale: 'TYAGARAH NSW' },
  { state: 'QLD', locale: 'UNDARA QLD' },
  { state: 'QLD', locale: 'URANDANGI QLD' },
  { state: 'NSW', locale: 'URANQUINTY' },
  { state: 'QLD', locale: 'VAN ROOK STATION QLD' },
  { state: 'QLD', locale: 'VICTOR ISLAND EAST QLD' },
  { state: 'QLD', locale: 'VICTOR ISLAND WEST QLD' },
  { state: 'NT', locale: 'VICTORIA HIGHWAY CORRIDOR' },
  { state: 'NT', locale: 'VICTORIA RIVER DOWNS NT' },
  { state: 'WA', locale: 'WA' },
  { state: 'NSW', locale: 'WAGGA WAGGA NSW' },
  { state: 'WA', locale: 'WAGIN WA' },
  { state: 'VIC', locale: 'WAHRING FIELD VIC' },
  { state: 'SA', locale: 'WAIKERIE SA' },
  { state: 'NSW', locale: 'WALCHA NSW' },
  { state: 'NSW', locale: 'WALGETT NSW' },
  { state: 'QLD', locale: 'WALLANGARRA' },
  { state: 'NSW', locale: 'WANAARING NSW' },
  { state: 'VIC', locale: 'WANGARATTA VIC' },
  { state: 'QLD', locale: 'WANGETTI' },
  { state: 'VIC', locale: 'WARANGA BASIN' },
  { state: 'WA', locale: 'WARBURTON WA' },
  { state: 'NSW', locale: 'WARIALDA NSW' },
  { state: 'NSW', locale: 'WARKWORTH NSW' },
  { state: 'NSW', locale: 'WARNERVALE NSW' },
  { state: 'QLD', locale: 'WARRABER ISLAND QLD' },
  { state: 'NT', locale: 'WARRABRI NT' },
  { state: 'VIC', locale: 'WARRACKNABEAL VIC' },
  { state: 'NSW', locale: 'WARREN NSW' },
  { state: 'VIC', locale: 'WARRNAMBOOL VIC' },
  { state: 'QLD', locale: 'WARWICK QLD' },
  { state: 'NT', locale: 'WATERLOO NT' },
  { state: 'QLD', locale: 'WATTS BRIDGE QLD' },
  { state: 'NT', locale: 'WAVE HILL NT' },
  { state: 'NSW', locale: 'WEDDERBURN NSW' },
  { state: 'QLD', locale: 'WEIPA QLD' },
  { state: 'NSW', locale: 'WELLINGTON NSW' },
  { state: 'NSW', locale: 'WENTWORTH NSW' },
  { state: 'WA', locale: 'WEST ANGELAS WA' },
  { state: 'WA', locale: 'WEST MUSGRAVE WA' },
  { state: 'VIC', locale: 'WEST SALE HRS-SEE VIC' },
  { state: 'NSW', locale: 'WEST WYALONG NSW' },
  { state: 'NT', locale: 'WESTERN HILLS' },
  { state: 'VIC', locale: 'WESTERN PORT' },
  { state: 'NSW', locale: 'WESTMEAD HOSPITAL NSW' },
  { state: 'NSW', locale: 'WHITE CLIFFS NSW' },
  { state: 'WA', locale: 'WHITE GUM WA' },
  { state: 'SA', locale: 'WHYALLA' },
  { state: 'SA', locale: 'WHYALLA SA' },
  { state: 'NT', locale: 'WICKHAM POINT' },
  { state: 'QLD', locale: 'WIDE BAY' },
  { state: 'NSW', locale: 'WILCANNIA NSW' },
  { state: 'SA', locale: 'WILLIAM CREEK SA' },
  { state: 'QLD', locale: 'WILLIAMSON QLD' },
  { state: 'NSW', locale: 'WILLIAMTOWN' },
  { state: 'NSW', locale: 'WILLIAMTOWN HRS-SEE NSW' },
  { state: 'NSW', locale: 'WILTON' },
  { state: 'WA', locale: 'WILUNA WA' },
  { state: 'WA', locale: 'WINDARLING WA' },
  { state: 'QLD', locale: 'WINDORAH QLD' },
  { state: 'QLD', locale: 'WINTON QLD' },
  { state: 'TAS', locale: 'WITHNELL BAY' },
  { state: 'TAS', locale: 'WITHNELL BAY SOUTH' },
  { state: 'NSW', locale: 'WOLGAN VALLEY HELIPORT NSW' },
  { state: 'NSW', locale: 'WOLLONGONG' },
  { state: 'NSW', locale: 'WOLLONGONG HELIPORT NSW' },
  { state: 'QLD', locale: 'WONDAI QLD' },
  { state: 'QLD', locale: 'WONDOOLA QLD' },
  { state: 'WA', locale: 'WOODIE WOODIE WA' },
  { state: 'SA', locale: 'WOOMERA' },
  { state: 'SA', locale: 'WOOMERA HRS-SEE SA' },
  { state: 'QLD', locale: 'WROTHAM PARK QLD' },
  { state: 'SA', locale: 'WUDINNA SA' },
  { state: 'QLD', locale: 'WUJAL WUJAL QLD' },
  { state: 'QLD', locale: 'WYANDRA QLD' },
  { state: 'VIC', locale: 'WYCHEPROOF VIC' },
  { state: 'WA', locale: 'WYNDHAM WA' },
  { state: 'TAS', locale: 'WYNYARD TAS' },
  { state: 'QLD', locale: 'WYREEMA QLD' },
  { state: 'WA', locale: 'YAMARNA WA' },
  { state: 'WA', locale: 'YAMPI SOUND' },
  { state: 'VIC', locale: 'YARRAM VIC' },
  { state: 'VIC', locale: 'YARRAWONGA VIC' },
  { state: 'WA', locale: 'YATHARAGGA' },
  { state: 'NSW', locale: 'YOUNG NSW' },
  { state: 'NT', locale: 'YUENDUMU NT' },
]

export const australianStates: AustralianState[] = [
  "ACT",
  "NSW",
  "NT",
  "QLD",
  "SA",
  "TAS",
  "VIC",
  "WA",
  "OTHER",
  "UNKNOWN",
]
export type AustralianState =
  | "ACT"
  | "NSW"
  | "NT"
  | "QLD"
  | "SA"
  | "TAS"
  | "VIC"
  | "WA"
  | "OTHER"
  | "UNKNOWN"

export const localeStateMap = rawLocaleStateMap